name: 'Get PR body snippet'
description: 'Get a snippet of the PR body based on a start and end regex.'
author: 'O'Mutt (Matt@OKeefe.dev)'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  start-regex:
    description: 'The start of the PR snippet'
    required: false
    default: '#.*?desc.*?'
  end-regex:
    description: 'The end of the PR snippet'
    required: false
    default: '#?'

# Define your outputs here.
outputs:
  snippet:
    description: 'The snippet of the PR body'

runs:
  using: node20
  main: dist/index.js
